name: Screenshot bollettino di domani e invio email

on:
  schedule:
    # 17:00 Europe/Rome -> 15:00 UTC (ora legale) e 16:00 UTC (ora solare)
    - cron: "0 15 * * *"
    - cron: "0 16 * * *"
  workflow_dispatch:
    inputs:
      force_send:
        description: "Forza invio anche fuori dall'orario 17:00 Europe/Rome?"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install playwright==1.46.0 requests
          python -m playwright install --with-deps chromium

      - name: Run script
        env:
          TARGET_URL: "https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita/"
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}      # 465 (SSL) o 587 (STARTTLS)
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: "luca.molini@cimafoundation.org"
          EMAIL_SUBJECT: "Bollettino di criticità — mappa di domani"
          EMAIL_BODY: "In allegato lo screenshot della mappa (fase previsionale di domani)."
          SCREENSHOT_NAME: "bollettino_domani.png"
          ROME_HOUR_GATE: "17"                     # invia solo alle 17:00 Europe/Rome
          FORCE_SEND: ${{ inputs.force_send }}     # "true" per forzare invio
        run: python send_bollettino_domani.py
