# .github/workflows/bollettino-domani.yml
name: Screenshot bollettino di domani e invio email

on:
  schedule:
    # 17:00 Europe/Rome -> 15:00 UTC (ora legale) e 16:00 UTC (ora solare)
    - cron: "0 15 * * *"
    - cron: "0 16 * * *"
  workflow_dispatch:
    inputs:
      force_send:
        description: "Forza invio anche fuori dall'orario 17:00 Europe/Rome?"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install playwright==1.46.0
          python -m playwright install --with-deps chromium

      - name: Run script
        id: run_script
        continue-on-error: true        # ⬅️ continua anche se il Python fallisce
        env:
          TARGET_URL: "https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita/"
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: "luca.molini@cimafoundation.org"
          EMAIL_SUBJECT: "Bollettino di criticità — mappa di domani"
          EMAIL_BODY: "In allegato lo screenshot della mappa (fase previsionale di domani)."
          SCREENSHOT_NAME: "bollettino_domani.png"
          ROME_HOUR_GATE: "17"
          FORCE_SEND: ${{ inputs.force_send }}
        run: python send_bollettino_domani.py

      - name: Upload screenshot artifact (always)
        if: always()                   # ⬅️ esegui comunque, anche se lo script ha fallito
        uses: actions/upload-artifact@v4
        with:
          name: bollettino-domani-${{ github.run_id }}
          path: |
            bollettino_domani_*.png
            bollettino_domani_latest.png
          retention-days: 14
          if-no-files-found: warn      # non fallire se non trova file
